create extension if not exists pgcrypto;
create type public.sale_status as enum ('paid','pending','cancelled');
create type public.payment_direction as enum ('incoming','outgoing');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, business_name text, full_name text, created_at timestamptz default now());
create table public.products (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, sku text, price numeric(12,2) not null check(price>=0), cost numeric(12,2) not null default 0 check(cost>=0), active boolean default true, created_at timestamptz default now());
create table public.sales (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, sale_number bigint generated always as identity, sold_at timestamptz not null default now(), payment_method text not null, status public.sale_status not null default 'paid', notes text, created_at timestamptz default now());
create table public.sale_items (id uuid primary key default gen_random_uuid(), sale_id uuid not null references public.sales(id) on delete cascade, product_id uuid references public.products(id) on delete set null, product_name text not null, quantity numeric(10,2) not null check(quantity>0), unit_price numeric(12,2) not null check(unit_price>=0), unit_cost numeric(12,2) not null default 0 check(unit_cost>=0));
create table public.expenses (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, category text not null, amount numeric(12,2) not null check(amount>=0), spent_at date not null default current_date, description text, created_at timestamptz default now());
create table public.payments (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, concept text not null, amount numeric(12,2) not null check(amount>=0), direction public.payment_direction not null, method text not null, status public.sale_status not null default 'paid', paid_at date not null default current_date, notes text, created_at timestamptz default now());
create index products_user_idx on public.products(user_id); create index sales_user_date_idx on public.sales(user_id,sold_at desc); create index expenses_user_date_idx on public.expenses(user_id,spent_at desc); create index payments_user_date_idx on public.payments(user_id,paid_at desc); create index sale_items_sale_idx on public.sale_items(sale_id);

alter table public.profiles enable row level security; alter table public.products enable row level security; alter table public.sales enable row level security; alter table public.sale_items enable row level security; alter table public.expenses enable row level security; alter table public.payments enable row level security;
create policy "own profiles" on public.profiles for all using(auth.uid()=id) with check(auth.uid()=id); create policy "own products" on public.products for all using(auth.uid()=user_id) with check(auth.uid()=user_id); create policy "own sales" on public.sales for all using(auth.uid()=user_id) with check(auth.uid()=user_id); create policy "own sale items" on public.sale_items for all using(exists(select 1 from public.sales s where s.id=sale_id and s.user_id=auth.uid())) with check(exists(select 1 from public.sales s where s.id=sale_id and s.user_id=auth.uid())); create policy "own expenses" on public.expenses for all using(auth.uid()=user_id) with check(auth.uid()=user_id); create policy "own payments" on public.payments for all using(auth.uid()=user_id) with check(auth.uid()=user_id);

create view public.sales_overview with (security_invoker=true) as select s.id,'NV-'||s.sale_number sale_number,s.sold_at,s.payment_method,s.status::text,si.product_name,si.quantity,si.unit_price,si.unit_cost,(si.quantity*si.unit_price) subtotal,(si.quantity*(si.unit_price-si.unit_cost)) profit from public.sales s join public.sale_items si on si.sale_id=s.id;
