-- Esquema aplicado al proyecto fmrcitmlhhwqbrsrsxfm.
-- Ejecutar sobre una base nueva. La migración reemplaza el prototipo sin datos.
drop view if exists public.sales_overview;
drop table if exists public.sale_items cascade; drop table if exists public.sales cascade;
drop table if exists public.products cascade; drop table if exists public.expenses cascade;
drop table if exists public.payments cascade; drop table if exists public.profiles cascade;
drop type if exists public.sale_status cascade; drop type if exists public.payment_status cascade;
create type public.sale_status as enum ('completed','pending','cancelled');
create type public.payment_status as enum ('paid','pending','cancelled');
create table public.profiles(id uuid primary key default gen_random_uuid(),user_id uuid not null unique references auth.users(id) on delete cascade,name text not null default '',email text not null default '',created_at timestamptz not null default now());
create table public.products(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,name text not null,description text,category text not null default 'Otros',sale_price numeric(14,2) not null check(sale_price>=0),cost_price numeric(14,2) not null default 0 check(cost_price>=0),stock integer not null default 0 check(stock>=0),active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.sales(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,total numeric(14,2) not null default 0 check(total>=0),total_cost numeric(14,2) not null default 0 check(total_cost>=0),profit numeric(14,2) generated always as (total-total_cost) stored,payment_method text not null,status public.sale_status not null default 'completed',notes text,sold_at timestamptz not null default now(),created_at timestamptz not null default now());
create table public.sale_items(id uuid primary key default gen_random_uuid(),sale_id uuid not null references public.sales(id) on delete cascade,product_id uuid not null references public.products(id) on delete restrict,quantity integer not null check(quantity>0),unit_price numeric(14,2) not null check(unit_price>=0),unit_cost numeric(14,2) not null check(unit_cost>=0),subtotal numeric(14,2) generated always as (quantity*unit_price) stored,profit numeric(14,2) generated always as (quantity*(unit_price-unit_cost)) stored);
create table public.expenses(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,name text not null,category text not null,amount numeric(14,2) not null check(amount>=0),description text,expense_date date not null default (timezone('America/Argentina/Buenos_Aires',now()))::date,created_at timestamptz not null default now());
create table public.payments(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,concept text not null,amount numeric(14,2) not null check(amount>=0),payment_method text not null,status public.payment_status not null default 'paid',payment_date date not null default (timezone('America/Argentina/Buenos_Aires',now()))::date,notes text,created_at timestamptz not null default now());
create index products_user_idx on public.products(user_id); create index sales_user_sold_idx on public.sales(user_id,sold_at desc); create index sale_items_sale_idx on public.sale_items(sale_id); create index expenses_user_date_idx on public.expenses(user_id,expense_date desc); create index payments_user_date_idx on public.payments(user_id,payment_date desc);
alter table public.profiles enable row level security; alter table public.products enable row level security; alter table public.sales enable row level security; alter table public.sale_items enable row level security; alter table public.expenses enable row level security; alter table public.payments enable row level security;
create policy profiles_owner on public.profiles for all using(user_id=auth.uid()) with check(user_id=auth.uid()); create policy products_owner on public.products for all using(user_id=auth.uid()) with check(user_id=auth.uid()); create policy sales_owner on public.sales for all using(user_id=auth.uid()) with check(user_id=auth.uid()); create policy sale_items_owner on public.sale_items for all using(exists(select 1 from public.sales s where s.id=sale_id and s.user_id=auth.uid())) with check(exists(select 1 from public.sales s where s.id=sale_id and s.user_id=auth.uid())); create policy expenses_owner on public.expenses for all using(user_id=auth.uid()) with check(user_id=auth.uid()); create policy payments_owner on public.payments for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create function public.set_updated_at() returns trigger language plpgsql set search_path='' as $$begin new.updated_at=now();return new;end$$; create trigger products_updated before update on public.products for each row execute function public.set_updated_at();
create function public.handle_new_user() returns trigger language plpgsql security definer set search_path='' as $$begin insert into public.profiles(user_id,name,email) values(new.id,coalesce(new.raw_user_meta_data->>'name',''),coalesce(new.email,''));return new;end$$; create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
revoke all on function public.handle_new_user() from public, anon, authenticated;
create function public.create_sale(p_items jsonb,p_payment_method text,p_status public.sale_status default 'completed',p_notes text default null,p_sold_at timestamptz default now()) returns uuid language plpgsql security invoker set search_path='' as $$declare v_sale uuid;v_total numeric:=0;v_cost numeric:=0;r jsonb;p public.products%rowtype;q integer;begin if jsonb_array_length(p_items)=0 then raise exception 'La venta requiere productos';end if;for r in select * from jsonb_array_elements(p_items) loop q=(r->>'quantity')::int;select * into p from public.products where id=(r->>'product_id')::uuid and user_id=auth.uid() for update;if not found then raise exception 'Producto no encontrado';end if;if p.stock<q then raise exception 'Stock insuficiente para %',p.name;end if;v_total:=v_total+p.sale_price*q;v_cost:=v_cost+p.cost_price*q;end loop;insert into public.sales(user_id,total,total_cost,payment_method,status,notes,sold_at) values(auth.uid(),v_total,v_cost,p_payment_method,p_status,p_notes,p_sold_at) returning id into v_sale;for r in select * from jsonb_array_elements(p_items) loop q=(r->>'quantity')::int;select * into p from public.products where id=(r->>'product_id')::uuid;insert into public.sale_items(sale_id,product_id,quantity,unit_price,unit_cost) values(v_sale,p.id,q,p.sale_price,p.cost_price);update public.products set stock=stock-q where id=p.id;end loop;return v_sale;end$$;
grant execute on function public.create_sale(jsonb,text,public.sale_status,text,timestamptz) to authenticated;
